version: '3.7'

services:
  base:
    build: ./base
    volumes:
      - ./storage:/storage
    ports:
      - "2222:22"
    command: ["tail", "-f", "/dev/null"]
  
  mysql:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'p@ssword'

  volumes:
    db_data: {}